### ISSUE TITLE
about Fundamentals of Adaptive Filtering MATLAB programs ？ 

### ISSUE THREAD

**Issue by zuowanbushiwo** [braton/fadapt#1]
Hi  braton
    Now from this website  ftp://ftp.wiley.com/public/sci_tech_med/filtering/  Can't download matlab source，can you upload?
thanks!

**Comment by jontio** [comment]
it's the web browser that's stopping you. Download an ftp client and use that to get access rather than a web browser.

**Comment by zuowanbushiwo** [comment]
ok，thanks!

**Comment by gnss17** [comment]
？-------- 原始邮件 --------发件人： zuowanbushiwo ***@***.***>日期： 2022年4月24日周日 09:25收件人： braton/fadapt ***@***.***>抄送： Subscribed ***@***.***>主    题： Re: [braton/fadapt] about Fundamentals of Adaptive Filtering MATLAB programs ？  (#1)

ok，thanks!
